name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Prepare gh-pages for deployment (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          # enable file pattern globbing for rm command
          shopt -s extglob
          rm -rf !(pr-preview)
          echo "Cleaned gh-pages branch (preserved PR previews)"
          git add -A
          git commit -m "chore: clean gh-pages before redeploy" || echo "No changes to commit"

      - name: Deploy build to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # Deploys to: main: /, PR -> /pr-####
          destination_dir: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' ? '' : format('pr-preview/pr-{0}', github.event.pull_request.number) }}
          keep_files: true
          commit_message: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' ? 'chore: deploy main build' : format('chore: deploy preview for PR #{0}', github.event.pull_request.number) }}

      - name: Post PR comment
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const bodyText = 'Preview PR here:';
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${prNumber}/`;
            const body = `${bodyText}\n${previewUrl}`;
            
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: prNumber,
            });

            const existing = comments.find(c => c.user.type === "Bot" && c.body.includes(bodyText));
            if (existing) {
              await github.rest.issues.updateComment({
                ...context.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body,
              });
            }

  cleanup:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Remove PR preview build
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf pr-preview/pr-${{ github.event.pull_request.number }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: remove preview for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin gh-pages
